name: Detekt Demo

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  test-custom-rule:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Test detekt-custom-rule
        run: cd detekt-custom-rule && ./gradlew check --no-daemon

      - name: Publish detekt-custom-rule as a local maven artifact
        run: cd detekt-custom-rule && ./gradlew publishDetektRulePublicationToMavenLocal

      - name: Run detekt on DetektPlayground (with type resolution)
        run: cd DetektPlayground && ./gradlew detektMain

      - name: Archive detekt results
        uses: actions/upload-artifact@v3
        if: success() || failure() # run even if previous steps have failed
        with:
          name: detekt-results
          path: DetektPlayground/build/reports/detekt/*

      - name: Upload SARIF to GitHub using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure() # run even if previous steps have failed
        with:
          sarif_file: DetektPlayground/build/reports/detekt/main.sarif
